### ISSUE TITLE
Avaliações, Vendedor e Produtos

### ISSUE THREAD

**Issue by MatKurianski** [MatKurianski/project-ceres-backend#3]
Criar Model e controller das avaliações

- [x] Adicionar nova avaliação sobre tal produto.

- [ ] Remover avaliação

Produto

- [x] Retornar informações sobre produto: dessa forma:

```
{
   id,
   nome,
   preco,
   descricao,
   vendedor : {
       id,
       nome,
   },
   avaliacao
}
```

Acredito que seja necessário usar JOIN. Para calcular a avaliação, sei que existem funções do próprio SQL pra isso

Usuario

- [ ] Retornar informações do usuário dessa forma:

```
{
    id,
    nome,
    avaliacao,
    produtos: [] // mesma formatação de Produto acima
}
```

**Comment by LeviUSP** [comment]
A avaliação será dentro do mesmo m*c do produto??

**Comment by LeviUSP** [comment]
precisa da imagem tb no produto?
